.TH git-annex-checkpresentkey 1
.SH NAME
git-annex-checkpresentkey \- check if key is present in remote
.PP
.SH SYNOPSIS
git annex checkpresentkey \fBkey\fP \fB[remote]\fP
.PP
.SH DESCRIPTION
This plumbing\-level command verifies if the specified key's content
is present in the specified remote.
.PP
When no remote is specified, it verifies if the key's content is present
somewhere, checking accessible remotes until it finds the content.
.PP
Exits 0 if the content is verified present, or 1 if it is verified to not
be present. If there is a problem, the special exit code 100 is used,
and an error message is output to stderr.
.PP
.SH OPTIONS
.IP "\fB\-\-batch\fP"
.IP
Enables batch mode. In this mode, the \fBkey\fP is not specified at the
command line, but the \fBremote\fP may still be. Lines containing keys are
read from stdin, and a line is output with "1" if the key is verified to
be present, and "0" otherwise.
.IP
.SH SEE ALSO
git-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

