.TH git-annex-contentlocation 1
.SH NAME
git-annex-contentlocation \- looks up content for a key
.PP
.SH SYNOPSIS
git annex contentlocation \fB[key ...]\fP
.PP
.SH DESCRIPTION
This plumbing\-level command looks up filename used to store the content 
of a key. The filename is output to stdout. If the key's content is not
present in the local repository, nothing is output, and it exits nonzero.
.PP
.SH OPTIONS
.IP "\fB\-\-batch\fP"
.IP
Enable batch mode, in which a line containing the key is read from
stdin, the filename to its content is output to stdout (with a trailing
newline), and repeat.
.IP
Note that if a key's content is not present, an empty line is output to
stdout instead.
.IP
.SH SEE ALSO
git-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

