.TH git-remote-tor-annex 1
.SH NAME
git\-remote\-tor\-annex \- remote helper program to talk to git-annex over tor
.PP
.SH SYNOPSIS
git fetch tor\-annex::address.onion:port
.PP
git remote add tor tor\-annex::address.onion:port
.PP
.SH DESCRIPTION
This is a git remote helper program that allows git to pull and push
over tor(1), communicating with a tor hidden service.
.PP
The tor hidden service probably requires an authtoken to use it.
The authtoken can be provided in the environment variable
\fBGIT_ANNEX_P2P_AUTHTOKEN\fP. Or, if there is a file in 
\fB.git/annex/creds/\fP matching the onion address of the hidden
service, its first line is used as the authtoken.
.PP
.SH SEE ALSO
git\-remote\-helpers(1)
.PP
git-annex(1)
.PP
git-annex\-enable\-tor(1)
.PP
git-annex\-remotedaemon(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

