.TH git-annex-diffdriver 1
.SH NAME
git-annex-diffdriver \- external git diff driver shim
.PP
.SH SYNOPSIS
git annex diffdriver \fB\-\- cmd \-\-opts \-\-\fP
.PP
.SH DESCRIPTION
This is an external git diff driver shim. Normally, when using \fBgit diff\fP
with an external diff driver, the symlinks to annexed files are not set up
right, so the external diff driver cannot read them in order to perform
smart diffing of their contents. This command works around the problem,
by passing the fixed up files to the real external diff driver.
.PP
To use this, you will need to have installed some git external diff driver
command. This is not the regular diff command; it takes a git\-specific
input. See git's documentation of \fBGIT_EXTERNAL_DIFF\fP and
gitattributes(5)'s documentation of external diff drivers.
.PP
Configure git to use "git-annex diffdriver \-\- cmd params \-\-"
as the external diff driver, where cmd is the external diff
driver you want it to run, and params are any extra parameters to pass
to it. Note the trailing "\-\-", which is required.
.PP
For example, set \fBGIT_EXTERNAL_DIFF=git-annex diffdriver \-\- j\-c\-diff \-\-\fP
.PP
.SH SEE ALSO
git-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

