.TH git-annex-merge 1
.SH NAME
git-annex-merge \- merge changes from remotes
.PP
.SH SYNOPSIS
git annex merge [branch]
.PP
.SH DESCRIPTION
When run without any parameters, this performs the same merging (and merge
conflict resolution) that is done by the sync command, but without pushing
or pulling any data.
.PP
When a branch to merge is specified, this merges it, using the same merge
conflict resolution as the sync command. This is especially useful on
an adjusted branch, because it applies the same adjustment to the
branch before merging it.
.PP
When annex.resolvemerge is set to false, merge conflict resolution
will not be done.
.PP
.SH SEE ALSO
git-annex(1)
.PP
git-annex\-sync(1)
.PP
git-annex\-adjust(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

