.TH git-annex-proxy 1
.SH NAME
git-annex-proxy \- safely bypass direct mode guard (deprecated)
.PP
.SH SYNOPSIS
git annex proxy \fB\-\- git cmd [options]\fP
.PP
.SH DESCRIPTION
This command was for use in a direct mode repository, and such 
repositories are automatically updated to use an adjusted unlocked branch.
So, there's no reason to use this command any longer.
.PP
.SH SEE ALSO
git-annex(1)
.PP
git-annex\-direct(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

