.TH git-annex-reinit 1
.SH NAME
git-annex-reinit \- initialize repository, reusing old UUID
.PP
.SH SYNOPSIS
git annex reinit \fBuuid|description\fP
.PP
.SH DESCRIPTION
Normally, initializing a repository generates a new, unique identifier
(UUID) for that repository. Occasionally it may be useful to reuse a
UUID \-\- for example, if a repository got deleted, and you're
setting it back up.
.PP
Use this with caution; it can be confusing to have two existing
repositories with the same UUID. 
.PP
Make sure you run \fBgit annex fsck\fP after changing the UUID of a
repository to make sure location tracking information is recorded
correctly.
.PP
Like \fBgit annex init\fP, this attempts to enable any special remotes
that are configured with autoenable=true.
.PP
.SH SEE ALSO
git-annex(1)
.PP
git-annex\-init(1)
.PP
git-annex\-fsck(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

