.TH git-annex-lock 1
.SH NAME
git-annex-lock \- undo unlock command
.PP
.SH SYNOPSIS
git annex lock \fB[path ...]\fP
.PP
.SH DESCRIPTION
Use this to undo an unlock command if you don't want to modify
the files any longer, or have made modifications you want to discard.
.PP
.SH OPTIONS
.IP "file matching options"
.IP
The git-annex\-matching\-options(1)
can be used to specify files to lock.
.IP
.IP "\fB\-\-json\fP"
Enable JSON output. This is intended to be parsed by programs that use
git-annex. Each line of output is a JSON object.
.IP
.IP "\fB\-\-json\-error\-messages\fP"
Messages that would normally be output to standard error are included in
the json instead.
.IP
.SH SEE ALSO
git-annex(1)
.PP
git-annex\-add(1)
.PP
git-annex\-unlock(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

