.TH git-annex-resolvemerge 1
.SH NAME
git-annex-resolvemerge \- resolve merge conflicts
.PP
.SH SYNOPSIS
git annex resolvemerge
.PP
.SH DESCRIPTION
Resolves a conflicted merge, by adding both conflicting versions of the
file to the tree, using variants of their filename. This is done
automatically when using \fBgit annex sync\fP or \fBgit annex merge\fP.
.PP
Note that only merge conflicts that involve one or more annexed files
are resolved. Merge conflicts between two files that are not annexed
will not be automatically resolved.
.PP
.SH EXAMPLE
Suppose Alice commits a change to annexed file \fBfoo\fP, and Bob commits
a different change to the same file \fBfoo\fP. 
.PP
Merging between them will then fail, and git will present the
merge conflict as a file \fBfoo\fP pointing to one version of the
git-annex symlink, with \fBgit status\fP indicating that \fBfoo\fP has an
unresolved conflict.
.PP
Running \fBgit annex resolvemerge\fP in this situation will resolve the merge
conflict, by replacing the file \fBfoo\fP with files named like
\fBfoo.variant\-c696\fP and \fBfoo.variant\-f16a\fP. One of the files has the content
that Alice committed, and the other has the content that Bob committed.
.PP
The user can then examine the two variants of the file, and either merge
the two changes into a single file, or rename one of them back to \fBfoo\fP
and delete the other.
.PP
.SH SEE ALSO
git-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

