.TH git-annex-setkey 1
.SH NAME
git-annex-setkey \- sets annexed content for a key
.PP
.SH SYNOPSIS
git annex setkey key file
.PP
.SH DESCRIPTION
This plumbing\-level command makes the content of the specified key
be set to the specified file. The file is moved into the annex.
.PP
It's generally a better idea to use git-annex\-reinject(1) instead of
this command.
.PP
.SH SEE ALSO
git-annex(1)
.PP
git-annex\-reinject(1)
.PP
git-annex\-dropkey(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

