.TH git-annex-fix 1
.SH NAME
git-annex-fix \- fix up links to annexed content
.PP
.SH SYNOPSIS
git annex fix \fB[path ...]\fP
.PP
.SH DESCRIPTION
Fixes up symlinks that have become broken to again point to annexed
content.
.PP
This is useful to run manually when you have been moving the symlinks
around, but is done automatically when committing a change with git too.
.PP
Also, adjusts unlocked files to be copies or hard links as
configured by annex.thin.
.PP
.SH OPTIONS
.IP "file matching options"
.IP
The git-annex\-matching\-options(1)
can be used to specify files to fix.
.IP
.SH SEE ALSO
git-annex(1)
.PP
git-annex\-fsck(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

