.TH git-annex-rmurl 1
.SH NAME
git-annex-rmurl \- record file is not available at url
.PP
.SH SYNOPSIS
git annex rmurl \fB[file url ..]\fP
.PP
.SH DESCRIPTION
Record that the file is no longer available at the url.
.PP
Removing the last url will make git-annex no longer treat content as being
present in the web special remote.
.PP
.SH OPTIONS
.IP "\fB\-\-batch\fP"
.IP
Enables batch mode, in which lines are read from stdin.
Each line should contain the file, and the url to remove from that file,
separated by a single space.
.IP
.IP "\fB\-z\fP"
Makes the \fB\-\-batch\fP input be delimited by nulls instead of the usual
newlines.
.IP
.SH SEE ALSO
git-annex(1)
.PP
git-annex\-addurl(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

