.TH git-annex-findref 1
.SH NAME
git-annex-findref \- lists files in a git ref (deprecated)
.PP
.SH SYNOPSIS
git annex findref \fB[ref]\fP
.PP
.SH DESCRIPTION
This is the same as \fBgit annex find\fP with the \-\-branch option, and you're
encouraged to use that instead unless you need to support older versions of
git-annex.
.PP
.SH OPTIONS
Same as git-annex\-find(1)
.PP
.SH SEE ALSO
git-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

