.TH git-annex-indirect 1
.SH NAME
git-annex-indirect \- switch repository to indirect mode (deprecated)
.PP
.SH SYNOPSIS
git annex indirect
.PP
.SH DESCRIPTION
This command was used to switch a repository back from direct mode
indirect mode.
.PP
Now git-annex automatically converts direct mode repositories to v7
with adjusted unlocked branches, so this command does nothing.
.PP
.SH SEE ALSO
git-annex(1)
.PP
git-annex\-direct(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

