.TH git-annex-lookupkey 1
.SH NAME
git-annex-lookupkey \- looks up key used for file
.PP
.SH SYNOPSIS
git annex lookupkey \fB[file ...]\fP
.PP
.SH DESCRIPTION
This plumbing\-level command looks up the key used for a file in the
index. The key is output to stdout. If there is no key (because
the file is not present in the index, or is not a git-annex managed file),
nothing is output, and it exits nonzero.
.PP
.SH OPTIONS
.IP "\fB\-\-batch\fP"
.IP
Enable batch mode, in which a line containing the filename is read from
stdin, the key is output to stdout (with a trailing newline), and repeat.
.IP
Note that if there is no key corresponding to the file, an empty line is
output to stdout instead.
.IP
.IP "\fB\-z\fP"
Makes the \fB\-\-batch\fP input be delimited by nulls instead of the usual
newlines.
.IP
.SH SEE ALSO
git-annex(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

