.TH git-annex-direct 1
.SH NAME
git-annex-direct \- switch repository to direct mode (deprecated)
.PP
.SH SYNOPSIS
git annex direct
.PP
.SH DESCRIPTION
This used to switch a repository to use direct mode.
But direct mode is no longer used; git-annex automatically converts
direct mode repositories to v7 adjusted unlocked branches.
.PP
.SH SEE ALSO
git-annex(1)
.PP
git-annex\-indirect(1)
.PP
git-annex\-adjust(1)
.PP
.SH AUTHOR
Joey Hess <id@joeyh.name>
.PP
.PP

